Plugins/SequencePlugin/Source/SequencePlugin/Private/Config/Config.h
=> Preparing for release build

Plugins/SequencePlugin/Content/Core/Demonstration/BP_CustomSpectatorPawn.uasset, Plugins/SequencePlugin/Content/Core/Demonstration/BP_Encryptor.uasset, Plugins/SequencePlugin/Content/Core/Pawn_Components/AC_SequencePawn_Component.uasset, Plugins/SequencePlugin/Content/Core/Sqn_Mngrs/BP_SequenceManager.uasset, Plugins/SequencePlugin/Content/Core/Sqn_Mngrs/BP_SqncBkndMngr.uasset, Plugins/SequencePlugin/README.md, Plugins/SequencePlugin/Source/SequencePlugin/Private/Authenticator.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/NativeEncryptors/AndroidEncryptor.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/NativeEncryptors/WindowsEncryptor.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/SequenceBackendManager.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Public/Authenticator.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/NativeEncryptors/AndroidEncryptor.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/NativeEncryptors/GenericNativeEncryptor.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/NativeEncryptors/WindowsEncryptor.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/SequenceBackendManager.h, Plugins/SequencePlugin/Source/SequencePlugin/SequencePlugin.Build.cs, README.md
Includes implementation for windows based encryption!
Readme updates for 5.4 to ensure modernized XCode is enabled for future usage and compiling needs
Custom Encryptor pipeline is setup we can now hand in a custom encryptor if users so desire at the BP or C++ level
=> Windows secure key

Plugins/SequencePlugin/Content/Core/HUD_CORE/WB_Elemnts/Contacts/WBP_ContactDetailedScreen.uasset, Plugins/SequencePlugin/SequencePlugin.uplugin, Plugins/SequencePlugin/Source/SequencePlugin/Private/Native/IOS/objective_c/IOSOAuth.mm, SequenceUnreal.uproject
Fixes compilation issues for Apple platforms in preparation for publishing on Epic MarketPlace.
=> Fixes for mac platform

Plugins/SequencePlugin/SequencePlugin.uplugin, SequenceUnreal.uproject
Fixes the accidental removal of windows and android support in the .uplugin & .uproject files on master
=> Re adding Android and Windows support

Plugins/SequencePlugin/Apache_2_0_License.txt, Plugins/SequencePlugin/Config/DefaultSequencePlugin.ini, Plugins/SequencePlugin/Config/FilterPlugin.ini, Plugins/SequencePlugin/SequencePlugin.uplugin, SequenceUnreal.uproject
=> Adding apache license

Plugins/SequencePlugin/README.md, Plugins/SequencePlugin/SequencePlugin.uplugin, Plugins/SequencePlugin/Source/SequencePlugin/Private/Native/IOS/objective_c/IOSOAuth.mm, Plugins/SequencePlugin/Source/SequencePlugin/Private/Native/IOS/objective_c/NativeAppleEncryptor.h, Plugins/SequencePlugin/Source/SequencePlugin/Private/Native/IOS/objective_c/NativeAppleEncryptor.mm, Plugins/SequencePlugin/Source/SequencePlugin/Private/NativeEncryptors/AppleEncryptor.cpp, Plugins/SequencePlugin/Source/SequencePlugin/SequencePlugin.Build.cs, README.md, SequenceUnreal.uproject
Adds Apple encryptor for both IOS & OSX platforms,
Updates the IOS_Signin code to be better handled by the current supported version of the IOSSDK with Unreal Engine 5.4
=> Ios secure key

Plugins/SequencePlugin/Content/Core/Testing/BP_GeneralTesting.uasset, Plugins/SequencePlugin/Content/Core/Testing/GeneralTesting_BP.uasset, Plugins/SequencePlugin/SequencePlugin.uplugin, Plugins/SequencePlugin/Source/SequencePlugin/Private/GeneralTesting.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/GeneralTesting.h, Plugins/SequencePlugin/Source/SequencePlugin/Private/Sequence/SequenceAPI.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/Tests/TestSequenceAPI.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/Tests/TestSequenceAPI.h, Plugins/SequencePlugin/Source/SequencePlugin/Private/Transak.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/Transak.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/Sequence/SequenceAPI.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/TransakDataTypes.h, Plugins/SequencePlugin/Source/SequencePlugin/SequencePlugin.Build.cs, SequenceUnreal.uproject
Adds transak on ramp support,
Removes the beta mark off of the UPlugin
=> Transak on ramp

Plugins/SequencePlugin/README.md, README.md
Some readme updates for the next release
=> Updates to readme for Release

Plugins/SequencePlugin/Source/SequencePlugin/Private/Indexer/Indexer.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/Util/SequenceSupport.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Public/Util/SequenceSupport.h
Fixes issue with Networks not always working correctly due to incorrect URL's with the Indexer
=> HotFix for networks issue

Plugins/SequencePlugin/Content/Core/Demonstration/BP_CustomSpectatorPawn.uasset, Plugins/SequencePlugin/Content/Core/Pawn_Components/AC_SequencePawn_Component.uasset, Plugins/SequencePlugin/Source/SequencePlugin/Private/Tests/IndexerTests.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Public/Indexer/Structs/SeqGetTokenSuppliesArgs.h
Fixes issue with TokenSupplies Arguments being improper resulting in no data being received
=> Fix for tokensupplies not working properly

Plugins/SequencePlugin/Source/SequencePlugin/Private/Native/NativeOAuth.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Public/Indexer/Structs/SeqGetChainIDReturn.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/Indexer/Structs/SeqGetEtherBalanceReturn.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/Indexer/Structs/SeqVersionReturn.h
Fixes a few compiler issues that cropped during android packaging
=> Compiler fixes on android

Plugins/SequencePlugin/Source/SequencePlugin/Private/Indexer/Indexer.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/Util/Log.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/Util/Log.h
We need more request context when debugging issues.
=> Logging server request context

Plugins/SequencePlugin/Source/SequencePlugin/Private/Sequence/SequenceWalletQrCode.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Public/Sequence/SequenceWalletQrCode.h
Changed names and declared int32 for uint
=> Ide conflicts update

Plugins/SequencePlugin/Source/SequencePlugin/Private/Indexer/Indexer.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/RequestHandler.cpp
Made curl format log of requests and full content json string for response
=> Logs for requests and responses

Plugins/SequencePlugin/Source/SequencePlugin/Private/SequenceRPCManager.cpp
Handling empty fee options array in feeoptionsresponse
=> Empty fee options response

Plugins/SequencePlugin/Source/SequencePlugin/Public/Indexer/Structs/SeqGetTransactionHistoryReturn.h, Plugins/SequenceTests/Source/SequenceTests/Private/IndexerEndToEndTests/IndexerGetTransactionHistoryTest.cpp
Updated custom parser and included another test check
=> Fixes on transaction history return parsing

Plugins/SequencePlugin/Content/Core/Pawn_Components/AC_SequencePawn_Component.uasset, Plugins/SequencePlugin/Source/SequencePlugin/Private/Sequence/SequenceWalletBP.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Public/Sequence/SequenceWalletBP.h
Calls an callbacks for getidtoken, validatemessaegsignature, listaccounts api methods
=> Added missing bp support for intents

Plugins/SequencePlugin/Source/SequencePlugin/Private/Integrators/SequenceSessionsBP.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/SequenceAuthenticator.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/SequenceBackendManager.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/SequenceBackendManager.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/Integrators/SequenceSessionsBP.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/SequenceAuthenticator.h, README.md
New authentication functions exposed for #140
=> session tickets

Plugins/SequencePlugin/Source/SequencePlugin/Private/GeneralTesting.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/SequenceRPCManager.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/SequenceRPCManager.h, Plugins/SequencePlugin/Source/SequencePlugin/Private/Tests/IndexerTests.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Public/Indexer/Structs/SeqGetTokenSuppliesArgs.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/Indexer/Structs/SeqGetTransactionHistoryArgs.h
Updated function for how plugin version is accessed, been able to build plugin with Unreal 5.3 and had no issue.
Got rid of TOptional usage in a couple scripts as it was not compatible with UPROPERTY.
=> 240 pluginmanager returns a nullptr on windows

Plugins/SequencePlugin/Source/SequencePlugin/Private/Sequence/DelayedEncodingArgsBP.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Public/Sequence/DelayedEncodingArgsBP.h
UDelayedEncodingObjectArgsBP removed from DelayedEncodingArgsBP.cpp and DelayedEncodingArgsBP.h
=> Removed UDelayedEncodingObjectArgsBP

Plugins/SequencePlugin/Source/SequencePlugin/Private/SequenceRPCManager.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/SequenceRPCManager.h
Let's keep it as a constant string for now and ensure that with every release this value is increased.
=> Removed GetPluginVersion() from RPCManager

Plugins/SequencePlugin/Source/SequencePlugin/Private/ObjectHandler.h, Plugins/SequencePlugin/Source/SequencePlugin/Private/Sequence/SequenceAPI.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/SequenceRPCManager.cpp
=> chore: fix some typos in comment

Plugins/SequencePlugin/Source/SequencePlugin/Public/Util/SequenceSupport.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/Util/Structs/BE_Enums.h
=> Added Telos

Plugins/SequencePlugin/Source/SequencePlugin/Private/Integrators/SequencePayBP.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/Transak.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/Transak.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/Integrators/SequencePayBP.h
=> Added SequencePayBP subsystem with on ramp functions

Plugins/SequencePlugin/SequencePlugin.uplugin, Plugins/SequencePlugin/Source/SequencePlugin/Private/SequenceRPCManager.h
=> version bump to 1.5.1

Plugins/SequencePlugin/Source/SequencePlugin/Public/Util/SequenceSupport.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/Util/Structs/BE_Enums.h
=> Added moonbeam and testnet

Plugins/SequencePlugin/Source/SequencePlugin/Public/Util/SequenceSupport.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/Util/Structs/BE_Enums.h
=> Added Etherlink mainnet and testnet and XR1 mainnet

Config/SequenceConfig.ini, Plugins/SequencePlugin/Source/SequencePlugin/Public/Util/SequenceSupport.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/Util/Structs/BE_Enums.h
=> Added monad and somnia testnets

Plugins/SequencePlugin/SequencePlugin.uplugin, Plugins/SequencePlugin/Source/SequencePlugin/Private/SequenceRPCManager.h
=> Version bump to 1.6.0

Plugins/SequencePlugin/SequencePlugin.uplugin, Plugins/SequencePlugin/Source/SequencePlugin/Private/Integrators/SequenceIndexerBP.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/Integrators/SequenceSessionsBP.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/SequenceRPCManager.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/Integrators/SequenceIndexerBP.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/Integrators/SequenceSdkBP.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/Integrators/SequenceSessionsBP.h
=> Fixed private module included in public headers

Plugins/SequencePlugin/Source/SequencePlugin/Private/Marketplace/SequenceMarketplace.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Public/Marketplace/Structs/SeqSwapPrice.h
=> Fix swap API integration

Plugins/SequencePlugin/Source/SequencePlugin/Public/Sequence/SequenceFederationSupport.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/Sequence/SequenceResponseIntent.h
=> Rename PlayFab enum to SequencePlayFab to avoid naming conflicts

Plugins/SequencePlugin/Source/SequencePlugin/Public/Util/SequenceSupport.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/Util/Structs/BE_Enums.h
=> Added Frequency testnet

Plugins/SequencePlugin/Source/SequencePlugin/Public/Util/SequenceSupport.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/Util/Structs/BE_Enums.h
=> Added incentiv testnet

Plugins/SequencePlugin/Source/SequencePlugin/Private/Types/BinaryData.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/Types/ERC1155SaleContract.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Private/Types/ERC721SaleContract.cpp, Plugins/SequencePlugin/Source/SequencePlugin/Public/Indexer/Structs/SeqPage.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/Types/BinaryData.h
=> Removed page.page value and fixed incorrect sessionId error

Plugins/SequencePlugin/Source/SequencePlugin/Public/Util/SequenceSupport.h, Plugins/SequencePlugin/Source/SequencePlugin/Public/Util/Structs/BE_Enums.h
=> added incentiv testnet v2
